/**
 * Mock course data for the courses list component. This data simulates API responses and should be replaced with actual API calls in production. Contains 6 sample courses across different categories and difficulty levels.
 *
 * TODO: Replace with API integration - fetch from /api/courses endpoint
 *
 * Each course includes complete instructor information, ratings, pricing, and metadata for demonstration purposes
 */

import { Course } from '@/types/course';

/**
 * Default number of courses to display per page
 */
export const COURSES_PER_PAGE = 12;

/**
 * Mock courses array containing sample course data for development and testing
 */
export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'مقدمة في البرمجة',
    description:
      'تعلم أساسيات البرمجة من الصفر مع أمثلة عملية ومشاريع تفاعلية.',
    instructor: {
      id: '1',
      name: 'أحمد محمد',
      title: 'مطور برمجيات',
      avatar: '/avatars/instructor1.jpg',
      rating: 4.8,
      students: 1250,
      courses: 5,
      bio: 'خبير في البرمجة مع أكثر من 10 سنوات من الخبرة',
    },
    level: 'مبتدئ',
    category: 'برمجة',
    duration: '8 أسابيع',
    students: 1250,
    rating: 4.8,
    reviewCount: 89,
    price: 299,
    image: '/banar-cours.png',
    filesCount: 25,
    isOngoing: true,
    createdAt: '2023-10-01',
  },
  {
    id: '2',
    title: 'تطوير الويب بـ React',
    description: 'بناء تطبيقات ويب حديثة باستخدام React و Next.js.',
    instructor: {
      id: '2',
      name: 'فاطمة علي',
      title: 'مطورة ويب',
      avatar: '/avatars/instructor2.jpg',
      rating: 4.9,
      students: 890,
      courses: 3,
      bio: 'خبيرة في تطوير الويب مع خبرة واسعة في React',
    },
    level: 'متوسط',
    category: 'تطوير الويب',
    duration: '12 أسبوع',
    students: 890,
    rating: 4.9,
    reviewCount: 67,
    price: 499,
    image: '/banar-cours.png',
    filesCount: 40,
    isOngoing: false,
    createdAt: '2023-09-15',
  },
  {
    id: '3',
    title: 'قواعد البيانات المتقدمة',
    description: 'تعلم تصميم وإدارة قواعد البيانات المعقدة.',
    instructor: {
      id: '3',
      name: 'محمد حسن',
      title: 'خبير قواعد بيانات',
      avatar: '/avatars/instructor3.jpg',
      rating: 4.7,
      students: 456,
      courses: 4,
      bio: 'خبير في قواعد البيانات مع خبرة في SQL و NoSQL',
    },
    level: 'متقدم',
    category: 'قواعد البيانات',
    duration: '10 أسابيع',
    students: 456,
    rating: 4.7,
    reviewCount: 34,
    price: 399,
    image: '/banar-cours.png',
    filesCount: 35,
    isOngoing: true,
    createdAt: '2023-08-20',
  },
  {
    id: '4',
    title: 'تعلم الذكاء الاصطناعي',
    description: 'مقدمة شاملة في الذكاء الاصطناعي وتطبيقاته.',
    instructor: {
      id: '4',
      name: 'سارة أحمد',
      title: 'خبيرة ذكاء اصطناعي',
      avatar: '/avatars/instructor4.jpg',
      rating: 4.6,
      students: 2100,
      courses: 6,
      bio: 'خبيرة في الذكاء الاصطناعي وتعلم الآلة',
    },
    level: 'مبتدئ',
    category: 'ذكاء اصطناعي',
    duration: '6 أسابيع',
    students: 2100,
    rating: 4.6,
    reviewCount: 156,
    price: 349,
    image: '/banar-cours.png',
    filesCount: 30,
    isOngoing: false,
    createdAt: '2023-07-10',
  },
  {
    id: '5',
    title: 'أمان المعلومات',
    description: 'حماية الأنظمة والشبكات من التهديدات الأمنية.',
    instructor: {
      id: '5',
      name: 'علي سالم',
      title: 'خبير أمان معلومات',
      avatar: '/avatars/instructor5.jpg',
      rating: 4.5,
      students: 678,
      courses: 4,
      bio: 'خبير في أمان المعلومات والقرصنة الأخلاقية',
    },
    level: 'متوسط',
    category: 'أمان المعلومات',
    duration: '9 أسابيع',
    students: 678,
    rating: 4.5,
    reviewCount: 45,
    price: 449,
    image: '/banar-cours.png',
    filesCount: 28,
    isOngoing: true,
    createdAt: '2023-06-05',
  },
  {
    id: '6',
    title: 'تصميم واجهات المستخدم',
    description: 'تصميم تجارب مستخدم ممتازة باستخدام Figma و Adobe XD.',
    instructor: {
      id: '6',
      name: 'نور حسن',
      title: 'مصممة واجهات',
      avatar: '/avatars/instructor6.jpg',
      rating: 4.8,
      students: 1345,
      courses: 3,
      bio: 'مصممة واجهات مستخدم مع خبرة في UX/UI',
    },
    level: 'مبتدئ',
    category: 'تصميم',
    duration: '7 أسابيع',
    students: 1345,
    rating: 4.8,
    reviewCount: 98,
    price: 279,
    image: '/banar-cours.png',
    filesCount: 22,
    isOngoing: false,
    createdAt: '2023-05-20',
  },
];